apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ index .Values "cert-manager" "clusterIssuer" "name" }}
spec:
  acme:
    server: {{ index .Values "cert-manager" "clusterIssuer" "server" }}
    email: {{ index .Values "cert-manager" "clusterIssuer" "email" }}
    privateKeySecretRef:
      name: {{ index .Values "cert-manager" "clusterIssuer" "secretName" }}
    solvers:
    - http01:
        ingress:
          class: ingress-nginx